import '../profile_page_eleven_screen/widgets/userprofile_item_widget.dart';import 'bloc/profile_page_eleven_bloc.dart';import 'models/profile_page_eleven_model.dart';import 'models/userprofile_item_model.dart';import 'package:dos__front_end/core/app_export.dart';import 'package:dos__front_end/widgets/app_bar/appbar_leading_image.dart';import 'package:dos__front_end/widgets/app_bar/appbar_subtitle.dart';import 'package:dos__front_end/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';class ProfilePageElevenScreen extends StatelessWidget {const ProfilePageElevenScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<ProfilePageElevenBloc>(create: (context) => ProfilePageElevenBloc(ProfilePageElevenState(profilePageElevenModelObj: ProfilePageElevenModel()))..add(ProfilePageElevenInitialEvent()), child: ProfilePageElevenScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(extendBody: true, extendBodyBehindAppBar: true, appBar: _buildAppBar(context), body: Container(width: SizeUtils.width, height: SizeUtils.height, decoration: BoxDecoration(color: appTheme.whiteA700, gradient: LinearGradient(begin: Alignment(0.5, 0), end: Alignment(0.5, 1), colors: [appTheme.teal400.withOpacity(0.91), appTheme.teal20068, appTheme.whiteA700.withOpacity(0)])), child: Container(margin: EdgeInsets.only(left: 12.h, right: 6.h), padding: EdgeInsets.symmetric(horizontal: 10.h, vertical: 7.v), decoration: AppDecoration.outlineBlack900011.copyWith(borderRadius: BorderRadiusStyle.roundedBorder40), child: BlocSelector<ProfilePageElevenBloc, ProfilePageElevenState, ProfilePageElevenModel?>(selector: (state) => state.profilePageElevenModelObj, builder: (context, profilePageElevenModelObj) {return ListView.separated(physics: BouncingScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 9.v);}, itemCount: profilePageElevenModelObj?.userprofileItemList.length ?? 0, itemBuilder: (context, index) {UserprofileItemModel model = profilePageElevenModelObj?.userprofileItemList[index] ?? UserprofileItemModel(); return UserprofileItemWidget(model);});}))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 30.v, leadingWidth: 28.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDownBlack90001, margin: EdgeInsets.only(left: 12.h, top: 5.v, bottom: 8.v), onTap: () {onTapArrowDown(context);}), title: AppbarSubtitle(text: "msg_previous_bookings".tr, margin: EdgeInsets.only(left: 10.h))); } 
/// Navigates to the profilePageOneScreen when the action is triggered.
onTapArrowDown(BuildContext context) { NavigatorService.pushNamed(AppRoutes.profilePageOneScreen, ); } 
 }
